package respond

import (
	"fmt"
	"math"
	"strings"

	gh "vector-triage/internal/github"
	"vector-triage/internal/store"
)

type Formatter struct {
	SimilarityThreshold float64
	DuplicateThreshold  float64
}

func (f Formatter) Format(event gh.Event, results []store.FusedResult) string {
	_ = event
	if len(results) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString(gh.CommentMarker)
	b.WriteString("\n### 🔍 Triage Report\n\n")

	duplicate := findTopDuplicate(results, thresholdOrDefault(f.DuplicateThreshold, 0.92))
	if duplicate != nil {
		b.WriteString("> [!WARNING]\n")
		b.WriteString(fmt.Sprintf("> **Possible duplicate** of #%d (%s similar)\n", duplicate.Number, formatPercent(duplicate.DisplaySimilarity)))
		b.WriteString(">\n")
		b.WriteString(fmt.Sprintf("> %s\n\n", duplicate.Title))
	}

	b.WriteString(fmt.Sprintf("<details><summary>📋 Similar items found (%d)</summary>\n\n", len(results)))
	b.WriteString("| # | Title | Similarity | Status |\n")
	b.WriteString("|---|-------|-----------|--------|\n")
	for _, result := range results {
		b.WriteString(fmt.Sprintf("| #%d | %s | %s | %s |\n",
			result.Number,
			escapePipe(result.Title),
			formatPercent(result.DisplaySimilarity),
			statusIcon(result.State)+" "+result.State,
		))
	}
	b.WriteString("\n</details>\n\n")
	b.WriteString("---\n")
	b.WriteString("<sub>Generated by triage-bot</sub>\n")

	return b.String()
}

func findTopDuplicate(results []store.FusedResult, duplicateThreshold float64) *store.FusedResult {
	var best *store.FusedResult
	for i := range results {
		candidate := results[i]
		if candidate.DisplaySimilarity < duplicateThreshold {
			continue
		}
		if best == nil || candidate.DisplaySimilarity > best.DisplaySimilarity {
			copyCandidate := candidate
			best = &copyCandidate
		}
	}
	return best
}

func thresholdOrDefault(value, fallback float64) float64 {
	if value <= 0 {
		return fallback
	}
	return value
}

func formatPercent(score float64) string {
	if score < 0 {
		score = 0
	}
	if score > 1 {
		score = 1
	}
	return fmt.Sprintf("%d%%", int(math.Round(score*100)))
}

func statusIcon(state string) string {
	switch strings.ToLower(strings.TrimSpace(state)) {
	case "open":
		return "🟢"
	case "merged":
		return "🟣"
	default:
		return "⚫"
	}
}

func escapePipe(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "(no title)"
	}
	return strings.ReplaceAll(raw, "|", "\\|")
}
